### ISSUE TITLE
find ways to replace generic "community" with "event"

### ISSUE THREAD

**Issue by julielerman** [vtcodecamp/documents#1]
I think it might make more sense not to refer to "being banned from the community" because we can't really do that. We can ban someone from the event.

If this sounds reasonable (we are dealing with the event, not the entire community) Do you think it makes sense to go through and make that more clear in places it would make sense to do so?

**Comment by jason-pelletier** [comment]
I would add that the Slack channel is an example of another aspect of the "community".  I agree that we're not saying "you're banned from the larger local tech community"—because (at a minimum) that's beyond our scope.  But, if there was a situation where they were removed from the event, I would think that we might consider removing them from the Slack channel, perhaps.  If that's a possibility, then we should probably mention it in this document.  I kind of see these documents as relevant to anything that Vermont Code Camp does, though, most of which is at the annual events.  Thoughts?

**Comment by robhalevt** [comment]
Just to be clear, you mean the VT Code Camp Slack channel, right? The BTVDEV slack channel exists independent of VT Code Camp.

**Comment by jason-pelletier** [comment]
Exactly, just the Vermont Code Camp Slack channel (and any other virtual space specifically for Vermont Code Camp that might exist in the future).

**Comment by jason-pelletier** [comment]
I'm going to publish these documents so I'll close this issue, but I'm happy to revisit this if anyone wants to do so.
