### ISSUE TITLE
what to do in case of a problem

### ISSUE THREAD

**Issue by julielerman** [vtcodecamp/documents#2]
"If you are subject to or witness unacceptable behavior, or have any other concerns, please notify a community organizer as soon as possible via email at team@vtcodecamp.org."

"please find an Vermont Code Camp volunteer, they will be wearing VTCC8 t-shirts " ,,, "or notify asap etc..."?

**Comment by jason-pelletier** [comment]
Agreed—one of the open items for me was around notification.  Perhaps we still mention the email address if it isn't during an event (since they can't find one of us then).  However, during an event, they should find a person to notify and not rely on the email notification because of connectivity.  I'll make that update.

**Comment by jason-pelletier** [comment]
I just made an update. Depending upon how we handle the in-person events versus other community aspects (like Slack) referenced in #1, this may need to be updated again.
