### ISSUE TITLE
Suggestion for Diversity statement

### ISSUE THREAD

**Issue by robhalevt** [vtcodecamp/documents#3]
> Our goal is to create an inclusive, respectful event environment that invites participation from people of all races, ethnicities, genders, ages, abilities, religions, and sexual orientation.

Because all the other categories are plural, not singular, maybe we should say "sexual orientations."

Also, in the CoC we take care to say "religion (or lack thereof)." I'd like to see this say "religions (or lack thereof)" here, as well.

**Comment by jason-pelletier** [comment]
I made the update to religions as you've suggested. I had noticed that about "sexual orientation" being singular in the original, too. I checked with Maureen to see whether she thought this was intentional based on her experience with other such documents. It doesn't seem like it was intentional, so I updated it. Additionally, she recommended updating "genders" to "gender identities or expressions" (which I have done), and also adding "educational levels" (as this appears in other such documents, and it could be particularly important to mention considering our venue is a higher education institution).
